site_name: NEFU_China
theme: flatly
copyright: NEFU_China © 2021
nav:
  - Home: Home.md  
  - Team: 
      - Members: Team/Members.md
      - Attributions: Team/Attributions.md
  - Project: 
      - Description: Project/Description.md
      - Design: Project/Design.md
      - Result: Project/Result.md
      - Experiments: Project/Experiments.md
      - Notebook: Project/Notebook.md
      - Contribution: Project/Contribution.md
      - Demonstrate: Project/Demonstrate.md
  - Satefy: Satefy.md
